# Generated by Django 3.2 on 2021-04-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('regular', 'Regular'), ('fiction', 'Fiction'), ('novel', 'Novel')], max_length=10)),
            ],
        ),
    ]
