# Generated by Django 3.2 on 2021-04-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='borrow_charge',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='comments',
            field=models.CharField(help_text='Comment on status/condition of book', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='date_paid',
            field=models.DateTimeField(null=True),
        ),
    ]
