# Generated by Django 3.2 on 2021-04-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210409_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
