# Generated by Django 3.2 on 2021-04-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='internal_rating',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='books.book'),
        ),
    ]
